stage one, adding a statistics server
AleksandrKis/java-explore-with-me pull request #3
Opened 2023-07-02 19:58 UTC by AleksandrKis

2023-07-03 06:45 UTC, krylov-sergey-sergeevich requested changes
Привет, неплохо, давай чутка подрефакторим и будет зачет =)

2023-07-03 06:45 UTC, krylov-sergey-sergeevich commented on service-stats/client/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
`<version>${project.version}</version>`

2023-07-03 06:45 UTC, krylov-sergey-sergeevich commented on service-stats/client/pom.xml
> +        <dependency>
```
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <optional>true</optional>
        </dependency>
```

2023-07-03 06:45 UTC, krylov-sergey-sergeevich commented on service-stats/client/src/main/java/ru/practicum/StatClient.java
> +    private static final String STAT_SERVER_URL = "http://localhost:9090";
Помоему это хардкод, а это плохо давай через переменную приложения сделаем чтобы через `@Value` подтянуть

2023-07-03 06:45 UTC, krylov-sergey-sergeevich commented on service-stats/dto/src/main/java/ru/practicum/HitDto.java
> +    String timestamp;
Может так?
```
@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime timestamp;
```

2023-07-03 06:45 UTC, krylov-sergey-sergeevich commented on service-stats/client/src/main/java/ru/practicum/StatClient.java
> +    public ResponseEntity<Object> getStats(String start, String end, String uri, boolean unique) {
Я бы рекомендовал бы создать сущность в dto типо ViewsStatsRequest и в ней все нужные поля держать

2023-07-03 06:45 UTC, krylov-sergey-sergeevich commented on service-stats/dto/src/main/java/ru/practicum/StatResponseDto.java
```
@Getter
@ToString
@Builder(toBuilder = true)
public class ViewsStatsRequest {
	@Singular("uri")
	private Set<String> uris;

	@Builder.Default
	private LocalDateTime start = LocalDateTime.now().withHour(0).withMinute(0);

	@Builder.Default
	private LocalDateTime end = LocalDateTime.now();

	private boolean unique;

	private Integer limit;

	private String application;

	public boolean hasUriCondition() {
		return uris != null && !uris.isEmpty();
	}

	public boolean hasLimitCondition() {
		return limit != null && limit != 0;
	}
}
```

Пример сущности для запроса

2023-07-03 06:45 UTC, krylov-sergey-sergeevich commented on service-stats/server/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
`<version>${project.version}</version>`

2023-07-03 06:45 UTC, krylov-sergey-sergeevich commented on service-stats/server/src/main/java/ru/practicum/service/StatServiceImpl.java
> +    private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
("yyyy-MM-dd HH:mm:ss" - много где повторяем

2023-07-03 06:45 UTC, krylov-sergey-sergeevich commented on service-stats/server/src/main/java/ru/practicum/service/StatServiceImpl.java
> +    private LocalDateTime convertString(String time) {
Напрашивается класс DateUtils

2023-07-03 06:45 UTC, krylov-sergey-sergeevich commented on service-stats/server/src/main/resources/schema.sql
Неплохо, но можно чутка усложнить и сделать подобную структуру (это не обязательно, а скорее как еще один вид/мнение как можно было):
```
CREATE TABLE IF NOT EXISTS apps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(150) NOT NULL,
  CONSTRAINT pk_aps PRIMARY KEY (id),
  CONSTRAINT UQ_APPS_NAME UNIQUE(name)
);

CREATE TABLE IF NOT EXISTS endpoint_hit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  app_id BIGINT NOT NULL,
  uri VARCHAR(2048),
  ip VARCHAR(15) NOT NULL,
  ts TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CONSTRAINT pk_endpoint_hit PRIMARY KEY (id),
  CONSTRAINT FK_ENDPOINT_HIT_ON_APP FOREIGN KEY (app_id) REFERENCES apps (id)
);
```

2023-07-03 16:50 UTC, AleksandrKis commented on service-stats/client/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
Done!

2023-07-03 17:00 UTC, AleksandrKis commented on service-stats/client/pom.xml
> +        <dependency>
Done!

2023-07-03 17:40 UTC, AleksandrKis commented on service-stats/client/src/main/java/ru/practicum/StatClient.java
> +    private static final String STAT_SERVER_URL = "http://localhost:9090";
Done!

2023-07-04 01:18 UTC, AleksandrKis commented on service-stats/dto/src/main/java/ru/practicum/HitDto.java
> +    String timestamp;
Никак не получается ! Клиент не может десериализовать значения типа `LocalDateTime` из строки запроса в объект `HitDto` . Как будто игнорирует @JsonFormat над полем timestamp. То есть String timestamp - на здоровье, а `LocalDateTime` ни как не получается.

2023-07-04 11:11 UTC, AleksandrKis commented on service-stats/server/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
Done!

2023-07-04 11:39 UTC, AleksandrKis commented on service-stats/server/src/main/java/ru/practicum/service/StatServiceImpl.java
> +    private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Done!

2023-07-04 12:00 UTC, AleksandrKis commented on service-stats/server/src/main/java/ru/practicum/service/StatServiceImpl.java
> +    private LocalDateTime convertString(String time) {
Done !

2023-07-04 12:08 UTC, AleksandrKis commented on service-stats/server/src/main/resources/schema.sql
не сомневаюсь что к концу диплома (если доживу) я пойму твою задумку, но пока мне не очень понятно...

2023-07-04 14:32 UTC, AleksandrKis commented on service-stats/dto/src/main/java/ru/practicum/StatResponseDto.java
шикарная идея ! браво ! в очередной раз ...

2023-07-04 14:33 UTC, AleksandrKis commented on service-stats/client/src/main/java/ru/practicum/StatClient.java
> +    public ResponseEntity<Object> getStats(String start, String end, String uri, boolean unique) {
Done! спасибо .

2023-07-04 15:14 UTC, AleksandrKis commented
Обрати внимание ! как то изменился алгоритм мержа . 
![image](https://github.com/AleksandrKis/java-explore-with-me/assets/111588369/50cd7b34-7513-4559-ad9e-42708c954de7)

2023-07-05 05:24 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-07-05 14:42 UTC, merged