Main svc
AleksandrKis/java-explore-with-me pull request #4
Opened 2023-08-05 14:53 UTC by AleksandrKis

2023-08-05 15:02 UTC, AleksandrKis commented
05 августа 2023 года Завершил второй этап сервис мэйн.

2023-08-21 20:08 UTC, krylov-sergey-sergeevich requested changes
Привет, неплохо, давай доработаем

- Проверь пж что везде аннотации Transactional стоят где нужно
- Замечания по заметкам поправить

2023-08-21 20:59 UTC, AleksandrKis commented on service-main/src/main/java/ru/practicum/categories/models/Category.java
> +@Table(name = "categories", uniqueConstraints = @UniqueConstraint(columnNames = {"name"}))
исправлено!

2023-08-21 20:59 UTC, AleksandrKis commented on service-main/pom.xml
> +        <dependency>
Исправлено!

2023-08-21 21:04 UTC, AleksandrKis commented on service-main/src/main/java/ru/practicum/categories/models/Category.java
> +    public final boolean equals(Object o) {
Исправлено!

2023-08-21 21:19 UTC, AleksandrKis commented on service-stats/server/src/main/java/ru/practicum/exceptions/ErrorHandler.java
> +        log.error("ОШИБКА");
Исправлено !

2023-08-21 22:14 UTC, AleksandrKis commented on service-stats/dto/src/main/java/ru/practicum/ViewsStatsRequest.java
> +    public static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Исправлено!

2023-08-21 22:33 UTC, AleksandrKis commented on service-main/src/main/java/ru/practicum/users/storage/UserRepository.java
> +    List<User> findByIdIn(List<Long> ids, Pageable page);
это "метод на основе названия" (query creation). Такое название предлагает Идея когда создаёшь метод.
findByIds - Идея не понимает и начинает ругаться(Cannot resolve property 'ids').

2023-08-21 22:36 UTC, AleksandrKis commented on service-main/src/main/java/ru/practicum/users/models/User.java
> +        Class<?> oEffectiveClass = o instanceof HibernateProxy ? ((HibernateProxy) o)
Упростил !

2023-08-21 22:46 UTC, AleksandrKis commented on service-main/src/main/java/ru/practicum/events/dto/TimeDto.java
> +            this.end = convertTime(LocalDateTime.now().plusDays(7));
у нас в группе, большая дискуссия была на эту тему... многие - 100 лет делали в старте и + 100 лет на конечную дату. Для целей задания дельта в 7 дней, мне показалось вполне достаточна.

2023-08-21 23:08 UTC, AleksandrKis commented on service-stats/server/src/main/java/ru/practicum/exceptions/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
статус для UnknownStateException и  WrongTimePeriodException задают тесты Postman-а.(нам их дают для проверки первого этапа) BAD_REQUEST или провалишь тест.

2023-08-22 13:11 UTC, AleksandrKis commented on service-main/src/main/java/ru/practicum/events/dto/TimeDto.java
> +            this.end = convertTime(LocalDateTime.now().plusDays(7));
Серёженька, МОЛЮ позволить мне оставить мою реализацию! ...поскольку ТЗ не регламентирует алгоритмического решения ситуации отсутствия временных интервалов в запросе пользователя. После весьма долгих и безуспешных попыток создать запрос к репозиторию который бы учитывал null в место LocalDateTime , мне показалось решение подсказанное тобой, (на первом этапе стат-сервер ViewsStatsRequest ) весьма элегантным и сильно упрощающим запрос к базе.

2023-08-22 13:21 UTC, AleksandrKis commented on service-stats/dto/src/main/java/ru/practicum/ViewsStatsRequest.java
> +    private String start = LocalDateTime.now().withHour(0).withMinute(0).format(DATE_TIME_FORMATTER);
RestTemplate для метода которого собственно и создавался ViewsStatsRequest без проблем передаёт строки , а LocalDateTime почему то оборачивает в массив (квадратные скобки) что в свою очередь приводит к проблеме поиска ... вообщем передавая строки решил проблему которую иначе решить просто даже не понимаю как.

2023-08-22 13:24 UTC, AleksandrKis commented on service-stats/server/src/main/java/ru/practicum/exceptions/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
Понял ! но в данном случае поменять BAD_REQUEST на другой статус, без поломки Postman теста не получится.

2023-08-22 13:25 UTC, AleksandrKis commented on service-main/src/main/java/ru/practicum/events/models/AdminActionStatus.java
> +    public static AdminActionStatus validAdminActionStatus(String status) {
не понял пожелания ...

2023-08-22 16:16 UTC, krylov-sergey-sergeevich commented on service-stats/dto/src/main/java/ru/practicum/ViewsStatsRequest.java
> +    private String start = LocalDateTime.now().withHour(0).withMinute(0).format(DATE_TIME_FORMATTER);
Плохой аргумент "у меня не получилось" если сроки не горят я бы настоял бы дальше ковырять

2023-08-22 16:17 UTC, krylov-sergey-sergeevich commented on service-main/src/main/java/ru/practicum/users/storage/UserRepository.java
> +    List<User> findByIdIn(List<Long> ids, Pageable page);
Ааа ну попробуй написать Query сам и тогда название будет любое какое захочешь =)

2023-08-22 16:17 UTC, krylov-sergey-sergeevich commented on service-main/src/main/java/ru/practicum/events/models/AdminActionStatus.java
> +    public static AdminActionStatus validAdminActionStatus(String status) {
validAdminActionStatus -> of

2023-08-22 16:18 UTC, krylov-sergey-sergeevich commented on service-main/src/main/java/ru/practicum/events/dto/TimeDto.java
> +            this.end = convertTime(LocalDateTime.now().plusDays(7));
Реализация так себе, но почти все студенты так делают. Я скорее про число 7 оно ничего не говорит, выведи его в переменную и дай ему название

2023-08-22 16:59 UTC, AleksandrKis commented on service-main/src/main/java/ru/practicum/events/models/AdminActionStatus.java
> +    public static AdminActionStatus validAdminActionStatus(String status) {
всё равно не понимаю... может ты имеешь ввиду : AdminActionStatus.valueOfIgnoreCase(status) ?

2023-08-23 00:52 UTC, AleksandrKis commented on service-main/src/main/java/ru/practicum/events/dto/TimeDto.java
> +            this.end = convertTime(LocalDateTime.now().plusDays(7));
Done!

2023-08-23 01:13 UTC, AleksandrKis commented on service-main/src/main/java/ru/practicum/events/models/AdminActionStatus.java
> +    public static AdminActionStatus validAdminActionStatus(String status) {
Done!

2023-08-23 01:41 UTC, AleksandrKis commented on service-stats/dto/src/main/java/ru/practicum/ViewsStatsRequest.java
> +    private String start = LocalDateTime.now().withHour(0).withMinute(0).format(DATE_TIME_FORMATTER);
Готово! теперь по другому! Уверен можно гораздо изящней ...Но я не понимаю как ? Со строкой надёжней и понятней . Серёж  Я прям готов заплатить если ты научишь как LocalDateTime протащить через RestTemplate в необходимом формате и довести этот LocalDateTime до репозитория. Я поломал проект два раза и потом обратно - я в академ ушёл во второй ( и последний) , от отпуска отказался в пользу решения и уже вот две итерации из трёх потрачено и решения у меня нет ! ((  Может так(в смысле строкой, через клиент) то же можно?

2023-08-23 02:04 UTC, AleksandrKis commented
не суди строго !  давай фичу пилить.

2023-08-23 12:46 UTC, merged