Feature rating events
AleksandrKis/java-explore-with-me pull request #5
Opened 2023-08-25 18:33 UTC by AleksandrKis

2023-08-26 08:05 UTC, krylov-sergey-sergeevich requested changes
Привет
- Почему так много схем?
- Давай приведем проект к финальному состоянию и в readme составим крутое описание
а) используемые технологии
б) о чем проект + что делает проект
в) кто разработчик
г) как можно запустить проект локально (чтобы другие разработчики могли склонировать и запустить)
можно в readme сделать ссылку или отображение img вообщем привести в презентабельный вид

- Описание на англ , за это лайк =)
- Пару вопросов по коду отписал

2023-08-26 08:05 UTC, krylov-sergey-sergeevich commented on service-main/src/main/java/ru/practicum/ratings/RateController.java
> +    public ResponseDto hitRateToEvent(@PathVariable long userId,
hit почему такое название? Я правильно понимаю что мы тут добавляем рейтинг?

2023-08-26 08:05 UTC, krylov-sergey-sergeevich commented on service-main/src/main/java/ru/practicum/ratings/RateController.java
> +    public ResponseDto hitRateToEvent(@PathVariable long userId,
Если добавляем то можно еще @ResponseStatus(HttpStatus.CREATED)

2023-08-26 08:05 UTC, krylov-sergey-sergeevich commented on service-main/src/main/java/ru/practicum/ratings/service/RatingServiceImpl.java
> +    private static void checkChangeTime(LocalDateTime rateTime, String message) {
Почему статик методы?

2023-08-26 08:05 UTC, krylov-sergey-sergeevich commented on service-main/src/main/resources/schema.sql
> +    rate       BOOLEAN NOT NULL,
За что это поле отвечает почему оно true/false?

2023-08-26 14:51 UTC, AleksandrKis commented on service-main/src/main/java/ru/practicum/ratings/RateController.java
> +    public ResponseDto hitRateToEvent(@PathVariable long userId,
для меня HIT - есть, как из рогатки маленьким, липким шарком слайма залепили в событие своей оценкой и этот слайм влепился смачно со шлепком в в этот эвент и остался на нём для всех кричащим маркером оценки. потому и hit потому и метод так реализован "как выстрел с рогатки"... ну да ладно - это романтика object oriented programming.
Исправлено !
на HttpStatus.CREATED - Изменил !

2023-08-26 17:02 UTC, AleksandrKis commented on service-main/src/main/java/ru/practicum/ratings/service/RatingServiceImpl.java
> +    private static void checkChangeTime(LocalDateTime rateTime, String message) {
Если метод может быть статическим по контексту приложения, я делаю его статическим.
Это упрощает и понимание и ясность использования. Унитарность алгоритма метода это вторая причина .Ну и некоторая потенциальная эффективность по памяти, если унитарность таки будет задействована. Это как с переменной которая может быть final...

2023-08-26 17:26 UTC, AleksandrKis commented on service-main/src/main/resources/schema.sql
> +    rate       BOOLEAN NOT NULL,
... это и есть квинтэссенция фичи - его величество Rate (entity of the same name) ! суть так сказать оценки, аналоговое отношение в цифровой реализации: нравится / не нравится.
Поскольку подход к оценке своего отношения к чему либо весьма разнообразен. Был выбран наиболее эмоционально окрашенный - как в колизее: достоин или нет. Но если всё же хочется раскрыть своё:  нравится / не нравится Есть сообщение которое можно оставить
в совокупности с большим пальцем вверх или вниз.

2023-08-28 17:09 UTC, AleksandrKis commented
Поправил README.md

2023-08-29 04:51 UTC, krylov-sergey-sergeevich commented on service-main/src/main/java/ru/practicum/ratings/service/RatingServiceImpl.java
> +    private static void checkChangeTime(LocalDateTime rateTime, String message) {
В целом согласен, но лучше в сервисах делать статичные методы по минимуму, и если такие методы нужны то возможно их нужно выводить в отдельный класс

2023-08-29 04:53 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

-------------------------------

Ну все наше взаимодействие подходит к концу, желаю удачи с защитой и в работе!

Если будет  желание общаться, работать вместе или обсудить интересный пет-проект, я всегда открыт для этого, мои контакты:
тг https://t.me/kssergey
гитхаб знаешь

2023-08-29 12:26 UTC, merged